import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

export const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});
export const charter = localFont({
  src: [
    {
      path: "../../public/fonts/charter.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-charter",
});
export const degular = localFont({
  src: [
    {
      path: "../../public/fonts/degular.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-degular",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [
      "/favicon-new.ico",
      { url: "/favicon-new-32x32.png", sizes: "32x32" },
      { url: "/favicon-new-16x16.png", sizes: "16x16" },
    ],
    apple: "/apple-touch-icon-new.png",
    other: [
      {
        rel: "icon",
        url: "/favicon-new.svg",
        type: "image/svg+xml",
      },
    ],
  },
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
      </head>
      <body className={`${inter.variable} ${charter.variable} ${degular.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
